// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmLfsoBB7K3MGrpr6RRclLOIsPH5KRzK8',
    appId: '1:690578501051:web:2536a73609419cb133a89e',
    messagingSenderId: '690578501051',
    projectId: 'alphawhales-8a17c',
    authDomain: 'alphawhales-8a17c.firebaseapp.com',
    storageBucket: 'alphawhales-8a17c.firebasestorage.app',
    measurementId: 'G-49885P7RSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88XRo2h7LS_I9x66l8ZBjzL_eo6re5N0',
    appId: '1:690578501051:android:50155dac0529479e33a89e',
    messagingSenderId: '690578501051',
    projectId: 'alphawhales-8a17c',
    storageBucket: 'alphawhales-8a17c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjY4WNTSQmadtcXKIJ_O3twNuQ_moDrSc',
    appId: '1:690578501051:ios:0d0ead56a6468fcc33a89e',
    messagingSenderId: '690578501051',
    projectId: 'alphawhales-8a17c',
    storageBucket: 'alphawhales-8a17c.firebasestorage.app',
    iosBundleId: 'com.app.alphaWhales',
  );

}